<b>1. Create a function to perform basic arithmetic operations that includes
addition, subtraction, multiplication and division on a string number (e.g. &quot;12 +
24&quot; or &quot;23 - 21&quot; or &quot;12 // 12&quot; or &quot;12 * 21&quot;).
Here, we have 1 followed by a space, operator followed by another space
and 2. For the challenge, we are going to have only two numbers between 1
valid operator. The return value should be a number.
eval() is not allowed. In case of division, whenever the second number equals
&quot;0&quot; return -1.

In [9]:
def arithmetic_operation(instr):
    nums = instr.split()
    if nums[1] == '+':
        return int(nums[0]) + int(nums[2])
    elif nums[1] == '-':
        return int(nums[0]) - int(nums[2])
    elif nums[1] == '//':
        if nums[2]=='0':
            return -1
        else:
            return int(nums[0]) // int(nums[2])
    elif nums[1] == '*':
        return int(nums[0]) * int(nums[2])

arithmetic_operation(&quot;12 // 0&quot;)

In [10]:
arithmetic_operation("12 + 12")

24

In [11]:
arithmetic_operation("12 - 12")

0

In [12]:
arithmetic_operation("12 * 12")

144

In [13]:
arithmetic_operation("12 // 0")

-1

<b>2. Write a function that takes the coordinates of three points in the form of a
2d array and returns the perimeter of the triangle. The given points are the
vertices of a triangle on a two-dimensional plane.

In [22]:
import math
def perimeter(arg):
    x, y, z = tuple(arg)
    a = math.sqrt(math.pow(x[0]-y[0],2)+math.pow(x[1]-y[1],2))
    b = math.sqrt(math.pow(y[0]-z[0],2)+math.pow(y[1]-z[1],2))
    c = math.sqrt(math.pow(z[0]-x[0],2)+math.pow(z[1]-x[1],2))
    return round(a + b + c, 2)

In [23]:
perimeter( [ [15, 7], [5, 22], [11, 1] ] )

47.08

In [24]:
perimeter( [ [0, 0], [0, 1], [1, 0] ] )

3.41

In [25]:
perimeter( [ [-10, -10], [10, 10 ], [-10, 10] ] )

68.28

<b>3. A city skyline can be represented as a 2-D list with 1s representing
buildings. In the example below, the height of the tallest building is 4 (second-
most right column).
   <pre>
[[0, 0, 0, 0, 0, 0],
[0, 0, 0, 0, 1, 0],
[0, 0, 1, 0, 1, 0],
[0, 1, 1, 1, 1, 0],
[1, 1, 1, 1, 1, 1]]

Create a function that takes a skyline (2-D list of 0&#39;s and 1&#39;s) and returns the height of the tallest skyscraper.

In [41]:
import numpy as np

def tallest_skyscraper(arr):
    arr = np.array(arr)
    heights = np.sum(arr,axis=0)
    print(heights)
    return np.max(heights)

In [42]:
tallest_skyscraper([
[0, 0, 0, 0],
[0, 1, 0, 0],
[0, 1, 1, 0],
[1, 1, 1, 1]
])

[1 3 2 1]


3

In [43]:
tallest_skyscraper([
[0, 1, 0, 0],
[0, 1, 0, 0],
[0, 1, 1, 0],
[1, 1, 1, 1]
])

[1 4 2 1]


4

In [44]:
tallest_skyscraper([
[0, 0, 0, 0],
[0, 0, 0, 0],
[1, 1, 1, 0],
[1, 1, 1, 1]
])

[2 2 2 1]


2

<b>4. A financial institution provides professional services to banks and claims
charges from the customers based on the number of man-days provided.
Internally, it has set a scheme to motivate and reward staff to meet and
exceed targeted billable utilization and revenues by paying a bonus for each
day claimed from customers in excess of a threshold target.
This quarterly scheme is calculated with a threshold target of 32 days per
quarter, and the incentive payment for each billable day in excess of such
threshold target is shown as follows:
    <pre>
Days Bonus
0 to 32 days Zero
33 to 40 days SGD$325 per billable day
41 to 48 days SGD$550 per billable day
Greater than 48 days SGD$600 per billable day

<br>Write a function to read the billable days of an employee and return the bonus he/she has obtained in that quarter.

In [54]:
def bonus(days):
    income = 0
    days = days - 32
    
    if days<0:
        return 0
    
    if days > 8:
        income = income + 8*325
        days = days-8
    else:
        income = income+ days*325
        days = 0
    
    if days > 8:
        income = income + 8*550
        days = days-8
    else:
        income = income+ days*550
        days = 0
        
    if days>0:
        income = income+ days*600
        
    return income

In [55]:
bonus(15)

0

In [56]:
bonus(37)

1625

In [57]:
bonus(50)

8200

<b>5. A number is said to be Disarium if the sum of its digits raised to their
respective positions is the number itself.
Create a function that determines whether a number is a Disarium or not.

In [67]:
def is_disarium(num):
    numsum = 0
    for index, n in enumerate(str(num), 1):
        numsum = numsum + int(n)**index
    return numsum == num

In [68]:
is_disarium(75)

False

In [69]:
is_disarium(135)

True

In [70]:
is_disarium(544)

False

In [71]:
is_disarium(518)

True

In [72]:
is_disarium(466)

False

In [73]:
is_disarium(8)

True